export const users = [
  {
    id: 1,
    first_name: "Abbi",
    last_name: "Mulbery",
    email: "amulbery0@google.it",
    image: "http://dummyimage.com/141x100.png/ff4444/ffffff",
    height: 1.8,
  },
  {
    id: 2,
    first_name: "Gus",
    last_name: "Chatfield",
    email: "gchatfield1@google.ru",
    image: "http://dummyimage.com/250x100.png/cc0000/ffffff",
  },
  {
    id: 3,
    first_name: "Luise",
    last_name: "Sneesbie",
    email: "lsneesbie2@nature.com",
    image: "http://dummyimage.com/160x100.png/cc0000/ffffff",
  },
  {
    id: 4,
    first_name: "Quinn",
    last_name: "Gamell",
    email: "qgamell3@comsenz.com",
    image: "http://dummyimage.com/115x100.png/5fa2dd/ffffff",
  },
  {
    id: 5,
    first_name: "Sayers",
    last_name: "Queyos",
    email: "squeyos4@odnoklassniki.ru",
    image: "http://dummyimage.com/203x100.png/ff4444/ffffff",
    height: 1.6,
  },
  {
    id: 6,
    first_name: "Tamqrah",
    last_name: "Plott",
    email: "tplott5@booking.com",
    image: "http://dummyimage.com/127x100.png/5fa2dd/ffffff",
  },
  {
    id: 7,
    first_name: "Tabbatha",
    last_name: "Lingfoot",
    email: "tlingfoot6@drupal.org",
    image: "http://dummyimage.com/249x100.png/cc0000/ffffff",
  },
  {
    id: 8,
    first_name: "Arabella",
    last_name: "Leasor",
    email: "aleasor7@symantec.com",
    image: "http://dummyimage.com/245x100.png/5fa2dd/ffffff",
  },
  {
    id: 9,
    first_name: "Fulvia",
    last_name: "Theseira",
    email: "ftheseira8@booking.com",
    image: "http://dummyimage.com/160x100.png/5fa2dd/ffffff",
    height: 1.9,
  },
  {
    id: 10,
    first_name: "Sander",
    last_name: "Nelthropp",
    email: "snelthropp9@bluehost.com",
    image: "http://dummyimage.com/115x100.png/dddddd/000000",
  },
];
