const ActionTypes = {
  REST_LOADING: "REST_LOADING",
  REST_SUCCESS: "REST_SUCCESS",
  REST_ERROR: "REST_ERROR",
  PRODUCT_LOADING: "PRODUCT_LOADING",
  PRODUCT_SUCCESS: "PRODUCT_SUCCESS",
  PRODUCT_ERROR: "PRODUCT_ERROR",
  CART_LOADING: "CART_LOADING",
  CART_ERROR: "CART_ERROR",
  CART_SUCCESS: "CART_SUCCESS",
  ADD_TO_CART: "ADD_TO_CART",
  DELETE_FROM_CART: "DELETE_FROM_CART",
  UPDATE_CART: "UPDATE_CART",
};
export default ActionTypes;
