const ActionTypes = {
  REST_LOADING: "REST_LOADING",
  REST_SUCCESS: "REST_SUCCESS",
  REST_ERROR: "REST_ERROR",
  PRODUCT_LOADING: "PRODUCT_LOADING",
  PRODUCT_SUCCESS: "PRODUCT_SUCCESS",
  PRODUCT_ERROR: "PRODUCT_ERROR",
};
export default ActionTypes;
